import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';
import { createClient } from '@supabase/supabase-js';

// We use the service role key here to bypass RLS and write to the DB safely
const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(req: NextRequest) {
    try {
        // Mercado Pago webhook verification
        const xSignature = req.headers.get('x-signature') || '';
        const xRequestId = req.headers.get('x-request-id') || '';

        // MP docs state that x-signature contains ts and v1 separated by comma
        // Example: ts=123456,v1=abcdefg
        const parts = xSignature.split(',');
        let ts = '';
        let hash = '';

        for (const part of parts) {
            if (part.startsWith('ts=')) ts = part.replace('ts=', '');
            if (part.startsWith('v1=')) hash = part.replace('v1=', '');
        }

        // Verify webhook secret if configured
        const webhookSecret = process.env.MERCADOPAGO_WEBHOOK_SECRET;

        if (webhookSecret && ts && hash && xRequestId) {
            const urlInfo = req.nextUrl.searchParams;
            const dataID = urlInfo.get('data.id') || '';
            const manifest = `id:${dataID};request-id:${xRequestId};ts:${ts};`;

            const hmac = crypto.createHmac('sha256', webhookSecret);
            hmac.update(manifest);
            const computedSignature = hmac.digest('hex');

            if (computedSignature !== hash) {
                console.warn('Mercado Pago webhook signature mismatch.');
                return new NextResponse('Unauthorized Signature', { status: 403 });
            }
        }

        // Parse payload
        const body = await req.json();
        console.log('Received MP Webhook', body);

        const type = req.nextUrl.searchParams.get('type') || body.type;

        // We mostly care about "subscription_preapproval" updates
        if (type === 'subscription_preapproval') {
            const dataId = req.nextUrl.searchParams.get('data.id') || body.data?.id;

            if (!dataId) return new NextResponse('Missing Data ID', { status: 400 });

            // Fetch the preapproval details from MP directly
            const fetchResponse = await fetch(`https://api.mercadopago.com/preapproval/${dataId}`, {
                headers: {
                    Authorization: `Bearer ${process.env.MERCADOPAGO_ACCESS_TOKEN}`,
                },
            });

            const preapprovalData = await fetchResponse.json();

            if (preapprovalData.id) {
                // Find user by reading external_reference
                let externalData;
                try {
                    externalData = JSON.parse(preapprovalData.external_reference);
                } catch (e) {
                    // If unparseable or not generated by us, skip
                }

                if (externalData?.user_id && externalData?.plan_id) {
                    // Check if subscription exists in DB
                    const { data: existingSub } = await supabaseAdmin
                        .from('subscriptions')
                        .select('*')
                        .eq('mp_preapproval_id', preapprovalData.id)
                        .single();

                    if (existingSub) {
                        // Update
                        await supabaseAdmin.from('subscriptions').update({
                            status: preapprovalData.status,
                            updated_at: new Date().toISOString(),
                        }).eq('id', existingSub.id);
                    } else {
                        // Insert new record
                        await supabaseAdmin.from('subscriptions').insert({
                            profile_id: externalData.user_id,
                            mp_preapproval_id: preapprovalData.id,
                            plan_id: externalData.plan_id,
                            status: preapprovalData.status,
                            price: preapprovalData.auto_recurring.transaction_amount,
                        });
                    }
                }
            }
        }

        return new NextResponse('OK', { status: 200 });

    } catch (error) {
        console.error('Webhook error:', error);
        return new NextResponse('Internal Server Error', { status: 500 });
    }
}
